package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Category generated by hbm2java
 */
@ManagedBean(name="category")
@SessionScoped
public class Category implements java.io.Serializable {

	private int catid;
	private String catName;
	private String catDesc;
	private Set subCategories = new HashSet(0);


	public int getCatid() {
		return catid;
	}

	public void setCatid(int catid) {
		this.catid = catid;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getCatDesc() {
		return this.catDesc;
	}

	public void setCatDesc(String catDesc) {
		this.catDesc = catDesc;
	}

	public Set getSubCategories() {
		return this.subCategories;
	}

	public void setSubCategories(Set subCategories) {
		this.subCategories = subCategories;
	}

}
