package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryCost generated by hbm2java
 */
public class DeliveryCost implements java.io.Serializable {

	private int id;
	private Serializable zoneName;
	private double deliveryCost;
	private Set proOrders = new HashSet(0);

	public DeliveryCost() {
	}

	public DeliveryCost(int id, Serializable zoneName, double deliveryCost) {
		this.id = id;
		this.zoneName = zoneName;
		this.deliveryCost = deliveryCost;
	}

	public DeliveryCost(int id, Serializable zoneName, double deliveryCost, Set proOrders) {
		this.id = id;
		this.zoneName = zoneName;
		this.deliveryCost = deliveryCost;
		this.proOrders = proOrders;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Serializable getZoneName() {
		return this.zoneName;
	}

	public void setZoneName(Serializable zoneName) {
		this.zoneName = zoneName;
	}

	public double getDeliveryCost() {
		return this.deliveryCost;
	}

	public void setDeliveryCost(double deliveryCost) {
		this.deliveryCost = deliveryCost;
	}

	public Set getProOrders() {
		return this.proOrders;
	}

	public void setProOrders(Set proOrders) {
		this.proOrders = proOrders;
	}

}
