package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * Product generated by hbm2java
 */
@ManagedBean(name="product")
@SessionScoped
public class Product implements java.io.Serializable {

	private int proid;
	private SubCategory subCategory;
	private String proName;
	private int proQty;
	private int proPrice;
	private String proUrl;
	private String proDesc;
	private Set proOrderDetailses = new HashSet(0);

	

	public int getProid() {
		return proid;
	}

	public void setProid(int proid) {
		this.proid = proid;
	}

	public SubCategory getSubCategory() {
		return this.subCategory;
	}

	public void setSubCategory(SubCategory subCategory) {
		this.subCategory = subCategory;
	}

	public String getProName() {
		return this.proName;
	}

	public void setProName(String proName) {
		this.proName = proName;
	}

	public int getProQty() {
		return this.proQty;
	}

	public void setProQty(int proQty) {
		this.proQty = proQty;
	}

	public int getProPrice() {
		return this.proPrice;
	}

	public void setProPrice(int proPrice) {
		this.proPrice = proPrice;
	}

	public String getProUrl() {
		return this.proUrl;
	}

	public void setProUrl(String proUrl) {
		this.proUrl = proUrl;
	}

	public String getProDesc() {
		return this.proDesc;
	}

	public void setProDesc(String proDesc) {
		this.proDesc = proDesc;
	}

	public Set getProOrderDetailses() {
		return this.proOrderDetailses;
	}

	public void setProOrderDetailses(Set proOrderDetailses) {
		this.proOrderDetailses = proOrderDetailses;
	}

}
