package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProOrder generated by hbm2java
 */
public class ProOrder implements java.io.Serializable {

	private int orderid;
	private DeliveryCost deliveryCost;
	private ShopUser shopUser;
	private int proid;
	private Date orderDate;
	private int orderQty;
	private int totalPrice;
	private boolean orderStatus;
	private String proDesc;
	private Set proOrderDetailses = new HashSet(0);


	public DeliveryCost getDeliveryCost() {
		return this.deliveryCost;
	}

	public void setDeliveryCost(DeliveryCost deliveryCost) {
		this.deliveryCost = deliveryCost;
	}

	public ShopUser getShopUser() {
		return this.shopUser;
	}

	public void setShopUser(ShopUser shopUser) {
		this.shopUser = shopUser;
	}

	public int getOrderid() {
		return orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public int getProid() {
		return proid;
	}

	public void setProid(int proid) {
		this.proid = proid;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	public int getOrderQty() {
		return this.orderQty;
	}

	public void setOrderQty(int orderQty) {
		this.orderQty = orderQty;
	}

	public int getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(int totalPrice) {
		this.totalPrice = totalPrice;
	}

	public boolean isOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(boolean orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getProDesc() {
		return this.proDesc;
	}

	public void setProDesc(String proDesc) {
		this.proDesc = proDesc;
	}

	public Set getProOrderDetailses() {
		return this.proOrderDetailses;
	}

	public void setProOrderDetailses(Set proOrderDetailses) {
		this.proOrderDetailses = proOrderDetailses;
	}

}
