package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

/**
 * ProOrderDetails generated by hbm2java
 */
public class ProOrderDetails implements java.io.Serializable {

	private int orderDetail;
	private ProOrder proOrder;
	private Product product;
	private int proQty;

	public ProOrderDetails() {
	}

	public ProOrderDetails(int orderDetail, ProOrder proOrder, Product product, int proQty) {
		this.orderDetail = orderDetail;
		this.proOrder = proOrder;
		this.product = product;
		this.proQty = proQty;
	}

	public int getOrderDetail() {
		return this.orderDetail;
	}

	public void setOrderDetail(int orderDetail) {
		this.orderDetail = orderDetail;
	}

	public ProOrder getProOrder() {
		return this.proOrder;
	}

	public void setProOrder(ProOrder proOrder) {
		this.proOrder = proOrder;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public int getProQty() {
		return this.proQty;
	}

	public void setProQty(int proQty) {
		this.proQty = proQty;
	}

}
