package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * ShopUser generated by hbm2java
 */
@ManagedBean
@SessionScoped
public class ShopUser implements java.io.Serializable {

	private int userid;
	private UserRole userRole;
	private String userName;
	private String userPassword;
	private String userEmail;
	private Date regDate;
	private String contactNo;
	private Set proOrders = new HashSet(0);

	

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public UserRole getUserRole() {
		return this.userRole;
	}

	public void setUserRole(UserRole userRole) {
		this.userRole = userRole;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public Set getProOrders() {
		return this.proOrders;
	}

	public void setProOrders(Set proOrders) {
		this.proOrders = proOrders;
	}

}
