package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

/**
 * SubCategory generated by hbm2java
 */
@ManagedBean(name="subCategory")
@SessionScoped
public class SubCategory implements java.io.Serializable {

	private int subCatid;
	private Category category;
	private String catName;
	private String catDesc;
	private Set products = new HashSet(0);

	

	public int getSubCatid() {
		return subCatid;
	}

	public void setSubCatid(int subCatid) {
		this.subCatid = subCatid;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getCatDesc() {
		return this.catDesc;
	}

	public void setCatDesc(String catDesc) {
		this.catDesc = catDesc;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
