package DTO;
// Generated 06.Nis.2019 14:48:57 by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.FetchType;
import javax.persistence.OneToMany;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private int roleid;
	private String roleName;
	private Set shopUsers = new HashSet(0);

	

	public int getRoleid() {
		return roleid;
	}

	public void setRoleid(int roleid) {
		this.roleid = roleid;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getShopUsers() {
		return this.shopUsers;
	}

	public void setShopUsers(Set shopUsers) {
		this.shopUsers = shopUsers;
	}

}
